apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-hello
  labels:
    app: micro-hello
    repo: archean-micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-hello
  template:
    metadata:
      labels:
        app: micro-hello
        repo: archean-micros
    spec:
      containers:
        - name: micro-hello
          image: "micro-hello:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 3