apiVersion: apps/v1
kind: Deployment
metadata:
  name: micro-query
  labels:
    app: micro-query
    repo: archean-micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro-query
  template:
    metadata:
      labels:
        app: micro-query
        repo: archean-micros
    spec:
      containers:
        - name: micro-query
          image: "micro-query:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"