# consult https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v1
kind: Config
build:
  local:
    push: false
#    concurrency: 2
  artifacts:
    - image: app-hello
      context: ./app-hello/
    - image: api-gateway
      context: ./api-gateway/
    - image: archean-monitor
      context: ./monitor-archean/
      sync:
        infer:
          - 'src/**/*'
    - image: test-e2e
      context: ./test-e2e/
      sync:
        infer:
          - 'cypress/**/*.js'

deploy:
  kustomize: {}

profiles:
  - name: hotweb
    build:
      artifacts:
      - image: app-hello
        context: ./app-hello/
      - image: api-gateway
        context: ./api-gateway/
      - image: archean-monitor
        context: ./monitor-archean/
        sync:
          infer:
            - 'src/**/*'
      - image: app-web
        context: ./app-web/
        docker:
          target: prod
    deploy:
      kubeContext: docker-desktop

  - name: gcp
    build:
      googleCloudBuild:
        projectId: 'use-your-project-name'

#todo for test-e2e avoid rebuilds by syncing test scripts only
