apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: api-gateway
      context: ./api-gateway/
    - image: archean-monitor
      context: ./monitor-archean/
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: test-e2e
      context: ./test-e2e/
#      sync:
#        manual:
#          - src: 'cypress/**/*.js'
#            dest: .
      # use the space below to add your own micros
    - image: micro-query
      context: ./micro-query/


deploy:
  kustomize: {}
