# consult https://skaffold.dev/docs/references/yaml/
apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: app-web
      context: ./app-web/
    - image: app-hello
      context: ./app-hello/
    - image: api-gateway
      context: ./api-gateway/
    - image: archean-monitor
      context: ./monitor-archean/
      sync:
        manual:
          - src: 'src/**/*'
            dest: .
    - image: test-e2e
      context: ./test-e2e/
      sync:
        manual:
          - src: 'cypress/**/*.js'
            dest: .

deploy:
  kustomize: {}

#todo for test-e2e avoid rebuilds by syncing test scripts only
