apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: micro-hello
      context: ./micro-hello/
    - image: api-gateway
      context: ./api-gateway/
    - image: archean-monitor
      context: ./monitor-archean/
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
    - image: test-e2e
      context: ./test-e2e/
      sync:
        manual:
          - src: 'cypress/**/*.js'
            dest: .

deploy:
  kustomize: {}

#todo for test-e2e avoid rebuilds by syncing test scripts only
