apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-hello
  labels:
    app: app-hello
    repo: archean-micros
    app-type: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-hello
  template:
    metadata:
      labels:
        app: app-hello
        repo: archean-micros
    spec:
      containers:
        - name: app-hello
          image: "app-hello:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 1
            periodSeconds: 3