apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
    repo: archean-micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        repo: archean-micros
    spec:
      restartPolicy: Always
      terminationGracePeriodSeconds: 1
      containers:
        - name: api-gateway
          image: "api-gateway:latest"
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 3
            periodSeconds: 5