apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-e2e
  labels:
    app: test-e2e
    repo: archean-micros
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-e2e
  template:
    metadata:
      labels:
        app: test-e2e
        repo: archean-micros
    spec:
      containers:
        - name: test-e2e
          image: "test-e2e:latest"
          imagePullPolicy: IfNotPresent
          env:
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              memory: "32Mi"
              cpu: "10m"